# This is a basic workflow to help you get started with Actions

name: (test) macos

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deps_package_tag:
        description: 'deps package tag'
        type: string
        required: true
        default: "v8_12.4.254.21_r13"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prebuilt_godot_editor_macos:
    # The type of runner that the job will run on
    runs-on: macos-14

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with: 
          repository: godotengine/godot
          path: godot
          ref: 4.3

      - uses: actions/checkout@v4
        with:
          repository: ialex32x/GodotJS
          path: godot/modules/GodotJS
          lfs: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Runs a single command using the runners shell
      - name: Prerequisites
        run: pip install scons

      - name: Build Deps
        run: |
          curl -L https://github.com/ialex32x/GodotJS-Dependencies/releases/download/${{ github.event.inputs.deps_package_tag }}/${{ github.event.inputs.deps_package_tag }}.zip --output v8.zip
          7z x -ogodot/modules/GodotJS v8.zip
          sh godot/misc/scripts/install_vulkan_sdk_macos.sh

      # Runs a set of commands using the runners shell
      - name: Build for arm64
        run: |
          cd godot
          scons dev_build=yes p=macos arch=arm64
  
      - name: Prepare artifact
        run: |
          strip godot/bin/godot.*
          chmod +x godot/bin/godot.*
  
      - name: Upload
        uses: actions/upload-artifact@v4
        with: 
          path: godot/bin/*.*
          name: prebuilt_godot_editor_macos
        
